server:
  port: 9000
spring:
  application:
    name: sell-api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
zuul:
  sensitive-headers:
  routes:
    product:
      path: /product/**
      service-id: sell-product
      sensitive-headers:
    sell-product: /product/**
#  ignored-services:
#    -sell-product
#  ignored-patterns:
#    -/**/product/**
    